function [resultado]=consultadato()
%% Automate Importing Data by Generating Code Using the Database Explorer App
% This code reproduces the data obtained using the Database Explorer app by
% connecting to a database, executing a SQL query, and importing data into the
% MATLAB(R) workspace.

% Auto-generated by MATLAB (R2025b) and Database Toolbox Version 25.2 on 18-Apr-2026 08:47:47

%% Make connection to database
conn = database('mySQLB');

%Set query to execute on the database
query = ['SELECT ID_DATO, VALOR_X,VALOR_Y FROM matlab1104a.dato where estado=1 order by ID_DATO desc'];

%% Execute query and fetch results
data = fetch(conn,query);

%% Close connection to database
close(conn)

%% Clear variables
clear conn query
if isstruct(data)
    resultado=struct2table(data)
    elseif iscell(data)
        resultado = cell2table(data);
    else
        resultado = data
end